### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by sidmutha** [hasura/skor#1]
- [x] change binary name
- [x] write test: 
 - set up env
 - run tests
 - teardown
- [x] When to use and sample use-cases
- [x] Webhook and payload documentation for each type of webhook
- [x] How to use on Hasura
- [x] Diagram of how it works
- [x] Contributors/maintainers section

**Comment by 0x777** [comment]
@sidmutha reopen if needed
